#!/bin/bash

source $HOME/.cache/wal/colors.sh
OPTION=$(echo -e "Suspend\nReboot\nShutdown\nHibernate" | dmenu \
  -fn "Fira Mono:size=10" -nb "$color0" -nf "$color15" \
  -sb "$color2" -sf "$color0" -dim "0.5" -b -i -p "Option:")

case $OPTION in
  Suspend)
    sudo zzz
    ;;
  Reboot)
    sudo reboot
    ;;
  Shutdown)
    sudo poweroff
    ;;
  Hibernate)
    sudo ZZZ
    ;;
  *)
    ;;
esac
