#!/bin/bash

source $HOME/.cache/wal/colors.sh
OPTION=$(echo -e "Suspend\nReboot\nShutdown\nHibernate" | dmenu \
  -fn "Hack Nerd Font:size=11" -nb "$color0" -nf "$color15" \
  -sb "$color2" -sf "$color0" -dim "0.5" -b -i -p "Option:")

case $OPTION in
  Suspend)
    systemctl suspend
    ;;
  Reboot)
    reboot
    ;;
  Shutdown)
    poweroff
    ;;
  Hibernate)
    systemctl hibernate
    ;;
  *)
    ;;
esac
